// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface BatchOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.Batch)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 seq_id = 1;</code>
   * @return The seqId.
   */
  long getSeqId();

  /**
   * <code>bool last = 2;</code>
   * @return The last.
   */
  boolean getLast();

  /**
   * <code>repeated string lookup_symbols = 3;</code>
   * @return A list containing the lookupSymbols.
   */
  java.util.List<java.lang.String>
      getLookupSymbolsList();
  /**
   * <code>repeated string lookup_symbols = 3;</code>
   * @return The count of lookupSymbols.
   */
  int getLookupSymbolsCount();
  /**
   * <code>repeated string lookup_symbols = 3;</code>
   * @param index The index of the element to return.
   * @return The lookupSymbols at the given index.
   */
  java.lang.String getLookupSymbols(int index);
  /**
   * <code>repeated string lookup_symbols = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the lookupSymbols at the given index.
   */
  com.google.protobuf.ByteString
      getLookupSymbolsBytes(int index);

  /**
   * <code>repeated .Challenger.Event events = 4;</code>
   */
  java.util.List<com.grpc.Event> 
      getEventsList();
  /**
   * <code>repeated .Challenger.Event events = 4;</code>
   */
  com.grpc.Event getEvents(int index);
  /**
   * <code>repeated .Challenger.Event events = 4;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .Challenger.Event events = 4;</code>
   */
  java.util.List<? extends com.grpc.EventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .Challenger.Event events = 4;</code>
   */
  com.grpc.EventOrBuilder getEventsOrBuilder(
      int index);
}
