// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: challenger.proto

package com.grpc;

public interface ResultQ2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:Challenger.ResultQ2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 benchmark_id = 1;</code>
   * @return The benchmarkId.
   */
  long getBenchmarkId();

  /**
   * <code>int64 batch_seq_id = 2;</code>
   * @return The batchSeqId.
   */
  long getBatchSeqId();

  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  java.util.List<com.grpc.CrossoverEvent> 
      getCrossoverEventsList();
  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  com.grpc.CrossoverEvent getCrossoverEvents(int index);
  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  int getCrossoverEventsCount();
  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  java.util.List<? extends com.grpc.CrossoverEventOrBuilder> 
      getCrossoverEventsOrBuilderList();
  /**
   * <code>repeated .Challenger.CrossoverEvent crossover_events = 3;</code>
   */
  com.grpc.CrossoverEventOrBuilder getCrossoverEventsOrBuilder(
      int index);
}
